### ISSUE TITLE
UnBan wont work

### ISSUE THREAD

**Issue by thenoname-gurl** [PlurrYT-Kolama/KolamaBot#1]
Error when running unban:

DiscordAPIError[10007]: Unknown Member
    at handleErrors (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/node_modules/@discordjs/rest/dist/index.js:1120:23)
    at async SequentialHandler.queueRequest (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/node_modules/@discordjs/rest/dist/index.js:953:14)
    at async _REST.request (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async GuildMemberManager._fetchSingle (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/node_modules/discord.js/src/managers/GuildMemberManager.js:221:18)
    at async Object.execute (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/commands/unban.js:18:24)
    at async Object.execute (/var/lib/pufferpanel/servers/ecea459f/KolamaBot/handles/events/interactionCreate.js:8:17) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Unknown Member', code: 10007 },
  code: 10007,
  status: 404,
  method: 'GET',
  url: 'https://discord.com/api/v10/guilds/guildid/members/memberid'
}

**Comment by thenoname-gurl** [comment]
Fully fixed issue: https://github.com/PlurrYT-Kolama/KolamaBot/commit/3a0ce4e0529b4ea788163705881fe0c5f4606f6a
